// Date: 10/04/2015 14:11:46
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.armadio.magicalinstrument.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelOrcishDrum extends ModelBase
{
  //fields
    ModelRenderer orcishDrumTop;
    ModelRenderer orcishDrumBot;
  
  public ModelOrcishDrum()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      orcishDrumTop = new ModelRenderer(this, 0, 0);
      orcishDrumTop.addBox(-5F, 0F, -5F, 10, 3, 10);
      orcishDrumTop.setRotationPoint(0F, 0F, 0F);
      orcishDrumTop.setTextureSize(64, 32);
      orcishDrumTop.mirror = true;
      setRotation(orcishDrumTop, 0F, 0F, 0F);
      orcishDrumBot = new ModelRenderer(this, 0, 13);
      orcishDrumBot.addBox(-4F, 3F, -4F, 8, 8, 8);
      orcishDrumBot.setRotationPoint(0F, 0F, 0F);
      orcishDrumBot.setTextureSize(64, 32);
      orcishDrumBot.mirror = true;
      setRotation(orcishDrumBot, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    orcishDrumTop.render(f5);
    orcishDrumBot.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
