// Date: 09/04/2015 19:20:41
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.armadio.magicalinstrument.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;


public class ModelMusicAltar extends ModelBase
{
  //fields
    ModelRenderer MusicAltarMid;
    ModelRenderer MusicAltarBot;
    ModelRenderer MusicAltarTop;
    ModelRenderer MusicAltarPillar1;
    ModelRenderer MusicAltarPillar2;
    ModelRenderer MusicAltarPillar3;
    ModelRenderer MusicAltarPillar4;
  
  public ModelMusicAltar()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      MusicAltarMid = new ModelRenderer(this, 0, 20);
      MusicAltarMid.addBox(-6F, 0F, -6F, 12, 10, 12);
      MusicAltarMid.setRotationPoint(0F, 12F, 0F);
      MusicAltarMid.setTextureSize(64, 64);
      MusicAltarMid.mirror = true;
      setRotation(MusicAltarMid, 0F, 0F, 0F);
      MusicAltarBot = new ModelRenderer(this, 0, 42);
      MusicAltarBot.addBox(-8F, 0F, -8F, 16, 2, 16);
      MusicAltarBot.setRotationPoint(0F, 22F, 0F);
      MusicAltarBot.setTextureSize(64, 64);
      MusicAltarBot.mirror = true;
      setRotation(MusicAltarBot, 0F, 0F, 0F);
      MusicAltarTop = new ModelRenderer(this, 0, 0);
      MusicAltarTop.addBox(-8F, 0F, -8F, 16, 4, 16);
      MusicAltarTop.setRotationPoint(0F, 8F, 0F);
      MusicAltarTop.setTextureSize(64, 64);
      MusicAltarTop.mirror = true;
      setRotation(MusicAltarTop, 0F, 0F, 0F);
      MusicAltarPillar1 = new ModelRenderer(this, 33, 1);
      MusicAltarPillar1.addBox(-1F, 0F, -1F, 2, 10, 2);
      MusicAltarPillar1.setRotationPoint(-6F, 12F, -6F);
      MusicAltarPillar1.setTextureSize(64, 64);
      MusicAltarPillar1.mirror = true;
      setRotation(MusicAltarPillar1, 0F, 0F, 0F);
      MusicAltarPillar2 = new ModelRenderer(this, 39, 1);
      MusicAltarPillar2.addBox(-1F, 0F, -1F, 2, 10, 2);
      MusicAltarPillar2.setRotationPoint(-6F, 12F, 6F);
      MusicAltarPillar2.setTextureSize(64, 64);
      MusicAltarPillar2.mirror = true;
      setRotation(MusicAltarPillar2, 0F, 0F, 0F);
      MusicAltarPillar3 = new ModelRenderer(this, 37, 1);
      MusicAltarPillar3.addBox(-1F, 0F, -1F, 2, 10, 2);
      MusicAltarPillar3.setRotationPoint(6F, 12F, 6F);
      MusicAltarPillar3.setTextureSize(64, 64);
      MusicAltarPillar3.mirror = true;
      setRotation(MusicAltarPillar3, 0F, 0F, 0F);
      MusicAltarPillar4 = new ModelRenderer(this, 37, 3);
      MusicAltarPillar4.addBox(-1F, 0F, -1F, 2, 10, 2);
      MusicAltarPillar4.setRotationPoint(6F, 12F, -6F);
      MusicAltarPillar4.setTextureSize(64, 64);
      MusicAltarPillar4.mirror = true;
      setRotation(MusicAltarPillar4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    MusicAltarMid.render(f5);
    MusicAltarBot.render(f5);
    MusicAltarTop.render(f5);
    MusicAltarPillar1.render(f5);
    MusicAltarPillar2.render(f5);
    MusicAltarPillar3.render(f5);
    MusicAltarPillar4.render(f5);
  }

    public void renderModel(float f){
        MusicAltarMid.render(f);
        MusicAltarBot.render(f);
        MusicAltarTop.render(f);
        MusicAltarPillar1.render(f);
        MusicAltarPillar2.render(f);
        MusicAltarPillar3.render(f);
        MusicAltarPillar4.render(f);
    }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
